/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.ostbot.sensi.view.DefiziteDefinieren.Spurenelemente;

import de.ostbot.sensi.view.ZustandErfassen.*;

/**
 *
 * @author Ostlord_UBA
 */
public class JPanelSpurenelemente extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSpurenelemente
     */
    public JPanelSpurenelemente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHintergrund = new javax.swing.JPanel();
        jLabelSpurenelemente = new javax.swing.JLabel();
        jLabelBor = new javax.swing.JLabel();
        jSliderBor = new javax.swing.JSlider();
        jLabelBorAnzeige = new javax.swing.JLabel();
        jLabelEisen = new javax.swing.JLabel();
        jSliderEisen = new javax.swing.JSlider();
        jLabelEisenAnzeige = new javax.swing.JLabel();
        jLabelKupfer = new javax.swing.JLabel();
        jSliderKupfer = new javax.swing.JSlider();
        jLabelKupferAnzeige = new javax.swing.JLabel();
        jLabelMangan = new javax.swing.JLabel();
        jSliderMangan = new javax.swing.JSlider();
        jLabelManganAnzeige = new javax.swing.JLabel();
        jLabelMolybdaen = new javax.swing.JLabel();
        jSliderMolybdaen = new javax.swing.JSlider();
        jLabelMolybdaenAnzeige = new javax.swing.JLabel();
        jLabelSchwefel = new javax.swing.JLabel();
        jSliderSchwefel = new javax.swing.JSlider();
        jLabelSchwefelAnzeige = new javax.swing.JLabel();
        jLabelSelen = new javax.swing.JLabel();
        jSliderSelen = new javax.swing.JSlider();
        jLabelSelenAnzeige = new javax.swing.JLabel();
        jLabelSilizium = new javax.swing.JLabel();
        jSliderSilizium = new javax.swing.JSlider();
        jLabelSiliziumAnzeige = new javax.swing.JLabel();
        jLabelZink = new javax.swing.JLabel();
        jSliderZink = new javax.swing.JSlider();
        jLabelZinkAnzeige = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabelSpurenelemente.setText("Spurenelemente:");

        jLabelBor.setText("Bor");

        jLabelBorAnzeige.setText("0");

        jLabelEisen.setText("Eisen");

        jLabelEisenAnzeige.setText("0");

        jLabelKupfer.setText("Kupfer");

        jLabelKupferAnzeige.setText("0");

        jLabelMangan.setText("Mangan");

        jLabelManganAnzeige.setText("0");

        jLabelMolybdaen.setText("Molybdän");

        jLabelMolybdaenAnzeige.setText("0");

        jLabelSchwefel.setText("Schwefel");

        jLabelSchwefelAnzeige.setText("0");

        jLabelSelen.setText("Selen");

        jLabelSelenAnzeige.setText("0");

        jLabelSilizium.setText("Silizium");

        jLabelSiliziumAnzeige.setText("0");

        jLabelZink.setText("Zink");

        jLabelZinkAnzeige.setText("0");

        javax.swing.GroupLayout jPanelHintergrundLayout = new javax.swing.GroupLayout(jPanelHintergrund);
        jPanelHintergrund.setLayout(jPanelHintergrundLayout);
        jPanelHintergrundLayout.setHorizontalGroup(
            jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                        .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBor)
                            .addComponent(jLabelEisen)
                            .addComponent(jLabelKupfer)
                            .addComponent(jLabelMangan)
                            .addComponent(jLabelMolybdaen)
                            .addComponent(jLabelSchwefel)
                            .addComponent(jLabelSelen)
                            .addComponent(jLabelSilizium)
                            .addComponent(jLabelZink))
                        .addGap(84, 84, 84)
                        .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderSilizium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSiliziumAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderZink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelZinkAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderSelen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSelenAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderSchwefel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSchwefelAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderMolybdaen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMolybdaenAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderMangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelManganAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderKupfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelKupferAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderEisen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEisenAnzeige))
                            .addGroup(jPanelHintergrundLayout.createSequentialGroup()
                                .addComponent(jSliderBor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBorAnzeige))))
                    .addComponent(jLabelSpurenelemente))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelHintergrundLayout.setVerticalGroup(
            jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHintergrundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSpurenelemente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderBor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBorAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderEisen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEisen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEisenAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderKupfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKupfer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKupferAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderMangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMangan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelManganAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderMolybdaen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMolybdaen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMolybdaenAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderSchwefel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSchwefel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSchwefelAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderSelen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelenAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderSilizium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSilizium, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSiliziumAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHintergrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderZink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZink, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZinkAnzeige, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHintergrund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHintergrund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBor;
    private javax.swing.JLabel jLabelBorAnzeige;
    private javax.swing.JLabel jLabelEisen;
    private javax.swing.JLabel jLabelEisenAnzeige;
    private javax.swing.JLabel jLabelKupfer;
    private javax.swing.JLabel jLabelKupferAnzeige;
    private javax.swing.JLabel jLabelMangan;
    private javax.swing.JLabel jLabelManganAnzeige;
    private javax.swing.JLabel jLabelMolybdaen;
    private javax.swing.JLabel jLabelMolybdaenAnzeige;
    private javax.swing.JLabel jLabelSchwefel;
    private javax.swing.JLabel jLabelSchwefelAnzeige;
    private javax.swing.JLabel jLabelSelen;
    private javax.swing.JLabel jLabelSelenAnzeige;
    private javax.swing.JLabel jLabelSilizium;
    private javax.swing.JLabel jLabelSiliziumAnzeige;
    private javax.swing.JLabel jLabelSpurenelemente;
    private javax.swing.JLabel jLabelZink;
    private javax.swing.JLabel jLabelZinkAnzeige;
    private javax.swing.JPanel jPanelHintergrund;
    private javax.swing.JSlider jSliderBor;
    private javax.swing.JSlider jSliderEisen;
    private javax.swing.JSlider jSliderKupfer;
    private javax.swing.JSlider jSliderMangan;
    private javax.swing.JSlider jSliderMolybdaen;
    private javax.swing.JSlider jSliderSchwefel;
    private javax.swing.JSlider jSliderSelen;
    private javax.swing.JSlider jSliderSilizium;
    private javax.swing.JSlider jSliderZink;
    // End of variables declaration//GEN-END:variables
}
